src/objects/AccountOpportunityRole__c.object
<CustomObject>
    <description>AccountOpportunityRole. Represents the TECHNICAL LANDSCAPE FOR THE PROJECT. Inspired by https://neo4j.lightning.force.com/lightning/r/organizer__ViewNodeMember__c/a7z3s0000004SCsAAM/view
MAINTENANCE:  DUPE DETECTION: for reporting cleanliness we use a Matching Rule + Duplicate Rule and as of 2020-03-06 the field it inspects is a compound key set by process builder therefore when adding new fields to the schema make sure to update that process builder.
PERMISSIONS: PermissionSets having description a7z3s0000004SCsAAM</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>accountOpportunityRoles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Technology Involved</label>
    <nameField>
        <displayFormat>AOR-{0000}</displayFormat>
        <label>Relevant Technology Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Technologies Involved</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <description>Status for contact, synced over from lead status on conversion</description>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Raw</fullName>
                </value>
                <value>
                    <fullName>Inquiry</fullName>
                </value>
                <value>
                    <fullName>MQL</fullName>
                </value>
                <value>
                    <fullName>SAL</fullName>
                </value>
                <value>
                    <fullName>SQL</fullName>
                </value>
                <value>
                    <fullName>SAO</fullName>
                </value>
                <value>
                    <fullName>Late Stage Opportunity</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
                <value>
                    <fullName>Recycle</fullName>
                </value>
                <value>
                    <fullName>Disqualified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DNBoptimizer__DnBContactRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Upon a successful match, Optimizer populates this field that links the Lead record to a specific D&amp;B Contact ID for display of the correct custom object with D&amp;B data.</description>
        <inlineHelpText>Upon a successful match, Optimizer populates this field that links the Lead record to a specific D&amp;B Contact ID for display of the correct custom object with D&amp;B data.</inlineHelpText>
        <label>ContactToDnB</label>
        <referenceTo>DNBoptimizer__DnBContactRecord__c</referenceTo>
        <relationshipLabel>ContactToDnB</relationshipLabel>
        <relationshipName>ContactToDnB</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LeanData__Matched_Buyer_Persona__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Matched Buyer Persona</label>
        <referenceTo>LeanData__Buyer_Persona__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Actuals_Last_Updated_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Actuals: Last Updated By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Current_Time_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Time Period</label>
        <referenceTo>pse__Time_Period__c</referenceTo>
        <relationshipLabel>Current Time Period For Resources</relationshipLabel>
        <relationshipName>CurrentTimePeriodForResources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Practice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Practice</label>
        <referenceTo>pse__Practice__c</referenceTo>
        <relationshipLabel>Resources</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>pse__Region__c</referenceTo>
        <relationshipLabel>Resources</relationshipLabel>
        <relationshipName>Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rh2__Describe__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Describe</label>
        <referenceTo>rh2__PS_Describe__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EmailMessage.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Email Messages</relationshipLabel>
        <relationshipName>Email_Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sugar_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Sugar Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/License_Key__c.object
<CustomObject>
    <description>Object used for storing Neo4J license keys</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with License Key request</description>
        <inlineHelpText>Opportunity associated with License Key request</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>License_Keys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Activation Key</label>
    <nameField>
        <displayFormat>LK-{0000}</displayFormat>
        <label>License Key Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activation Keys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Sugar_ID__c</fullName>
        <externalId>true</externalId>
        <label>Sugar ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Use_Case_Sub__c</fullName>
        <description>Subecategory Use cases</description>
        <label>Use Case Subcategory</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Use_Case__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Anti Money Laundering</fullName>
                </value>
                <value>
                    <fullName>Claim Processing</fullName>
                </value>
                <value>
                    <fullName>Compliance meta-data (GDPR, BSBS 239, MiFID II, Other)</fullName>
                </value>
                <value>
                    <fullName>Credit Risk Management</fullName>
                </value>
                <value>
                    <fullName>Customer 360 / KYC</fullName>
                </value>
                <value>
                    <fullName>Cyber Security</fullName>
                </value>
                <value>
                    <fullName>Data Governance</fullName>
                </value>
                <value>
                    <fullName>Data Integration</fullName>
                </value>
                <value>
                    <fullName>Digital Media MDM</fullName>
                </value>
                <value>
                    <fullName>Employee MDM</fullName>
                </value>
                <value>
                    <fullName>Enterprise MDM</fullName>
                </value>
                <value>
                    <fullName>Fraud Detection</fullName>
                </value>
                <value>
                    <fullName>Graph Analytics</fullName>
                </value>
                <value>
                    <fullName>Intelligence</fullName>
                </value>
                <value>
                    <fullName>Master Data (Customer 360 / KYC, Employee / Product / Sales / Supply Chain / Other)</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Product MDM</fullName>
                </value>
                <value>
                    <fullName>Sales MDM</fullName>
                </value>
                <value>
                    <fullName>Supply Chain MDM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Use_Case__c</fullName>
        <businessOwnerGroup>Sales</businessOwnerGroup>
        <description>This picklist contains values that apply to different use cases -- how and/or why the customer will use product(s). JIRA: SFDCSPT-460</description>
        <inlineHelpText>Select the value that best describes how and/or why the prospect will use the product(s) included in this oppotrunity.</inlineHelpText>
        <label>Use Case</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Embedded</fullName>
                </value>
                <value>
                    <fullName>Graph Based Search</fullName>
                </value>
                <value>
                    <fullName>Identity and Access Management</fullName>
                </value>
                <value>
                    <fullName>Knowledge Graph</fullName>
                </value>
                <value>
                    <fullName>Master &amp; Meta-Data Management</fullName>
                </value>
                <value>
                    <fullName>Network and IT Operations</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>Recommendations</fullName>
                </value>
                <value>
                    <fullName>Risk Management</fullName>
                </value>
                <value>
                    <fullName>Solutions Lab</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>pse__Practice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Practice</label>
        <referenceTo>pse__Practice__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>pse__Region__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <businessProcess>New</businessProcess>
        <label>New</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/pse__Practice__c.object
<CustomObject>
    <customHelpPage>pse__PracticeHelp</customHelpPage>
    <description>An entity that usually represents a product or business line. Practices are organized as an independent hierarchy determined by the Parent Practice field, with parent and child records of the same type. Every practice in the hierarchy may contain projects, resources (contacts), and other objects. The hierarchy allows roll-ups of revenue, cost, and time totals.</description>
    <fields>
        <fullName>pse__Actuals_Last_Updated_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Actuals: Last Updated By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Practices3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Current_Time_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Time Period</label>
        <referenceTo>pse__Time_Period__c</referenceTo>
        <relationshipLabel>Current Time Period For Practices</relationshipLabel>
        <relationshipName>CurrentTimePeriodForPractices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Practice</label>
    <nameField>
        <label>Practice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Practices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Region__c.object
<CustomObject>
    <customHelpPage>pse__RegionHelp</customHelpPage>
    <description>An entity that represents a geographic area in which you do business. Regions are organized as an independent hierarchy determined by the Parent Region field, with parent and child records of the same type. Every region in the hierarchy may contain projects, resources (contacts), and other objects. The hierarchy allows roll-ups of revenue, cost, and time totals.</description>
    <fields>
        <fullName>pse__Actuals_Last_Updated_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Actuals: Last Updated By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Regions3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Current_Time_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Time Period</label>
        <referenceTo>pse__Time_Period__c</referenceTo>
        <relationshipLabel>Current Time Period For Regions</relationshipLabel>
        <relationshipName>CurrentTimePeriodForRegions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SmartFactoryTest.cls
/*
   Copyright 2011 Mavens Consulting, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/   

@isTest
private class SmartFactoryTest {
    static {
        SmartFactory.FillAllFields = true; // increase test coverage without creating custom objects
        //SmartFactory.ExcludedFields.put('Contact',new Set<String>{'Opportunity__c'}); //exclude Opportunity__c lookup otherwise smartfactory would attempt opportunity creation
        //and  we dont have to navigate around opportunity validation rules in this test class.
        //SmartFactory.ExcludedFields.put('Account',new Set<String>{'Sugar_ID__c'});//we dont use Sugar crm anymore, so exclude the field to avoid dupe errors during tests.
        //SmartFactory.ExcludedFields.put('Contact',new Set<String>{'Sugar_ID__c'});//we dont use Sugar crm anymore, so exclude the field to avoid dupe errors during tests.
    }  
    
    static testMethod void createsSingleObjectWithSingleRequiredStringField() {
        Account account = (Account)SmartFactory.createSObject('Account');
        insert account;
        System.assert(account.Id != null);
        System.assert(account.Name != null);
    }
    
    /**
     * COMMENTED THIS BECAUSE Neo4j has a restricted picklist on opportunity Use_Case_Sub__c that depends on Use_case__c.  
     * The createsObjectWithCascadeSetsLookupField detects lookups and creates objects from it, 
     * which fails when picking an arbitrary picklist value.  The framework developer has a TODO mentioned to set default values, 
     * "Provide an field override map that allows callers to specify default values for specific objects and fields" https://github.com/mbotos/SmartFactory-for-Force.com
     * I tried to exclude the custom lookups that point to opportunity but either did not do it well enough because something with this method
     * trips the System.DmlException: Insert failed. First exception on row 0; first error: INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST, bad value for restricted picklist field: Anti Money Laundering: [Use_Case_Sub__c]  13516 Class.SmartFactory.setFieldValue: line 221, column 1 Class.SmartFactory.createSObject: line 71, column 1 Class.SmartFactory.createSObject: line 78, column 1 Class.SmartFactoryTest.createsObjectWithCascadeSetsLookupField: line 54, column 1
     */
    /*static testMethod void createsObjectWithCascadeSetsLookupField() {
        SmartFactory.ExcludedFields.put('Contact',new Set<String>{'Opportunity__c'}); //exclude Opportunity__c lookup otherwise smartfactory would attempt opportunity creation //and  we dont have to navigate around opportunity validation rules in this test class.
        SmartFactory.ExcludedFields.put('accountOpportunityRole__c',new Set<String>{'Opportunity__c'}); //exclude Opportunity__c lookup otherwise smartfactory would attempt opportunity creation //and  we dont have to navigate around opportunity validation rules in this test class.
        SmartFactory.ExcludedFields.put('EmailMessage',new Set<String>{'Opportunity__c'}); //exclude Opportunity__c lookup otherwise smartfactory would attempt opportunity creation //and  we dont have to navigate around opportunity validation rules in this test class.
        SmartFactory.ExcludedFields.put('License_Key__c',new Set<String>{'Opportunity__c'}); //exclude Opportunity__c lookup otherwise smartfactory would attempt opportunity creation //and  we dont have to navigate around opportunity validation rules in this test class.
        
        SmartFactory.ExcludedFields.put('Account',new Set<String>{'Sugar_ID__c'});//we dont use Sugar crm anymore, so exclude the field to avoid dupe errors during tests.
        SmartFactory.ExcludedFields.put('Contact',new Set<String>{'Sugar_ID__c'});//we dont use Sugar crm anymore, so exclude the field to avoid dupe errors during tests.
        
        SmartFactory.ExcludedFields.put('Opportunity',new Set<String>{'pse__Salesforce_User__c'});
        //exclude other custom lookup fields 
        SmartFactory.ExcludedFields.put('Opportunity',new Set<String>{'pse__Region__c'});
        SmartFactory.ExcludedFields.put('Opportunity',new Set<String>{'pse__Practice__c'});
        SmartFactory.ExcludedFields.put('Opportunity',new Set<String>{'Opportunity__c'});
        SmartFactory.ExcludedFields.put('Opportunity',new Set<String>{'LeanData__Matched_Buyer_Persona__c'});
        SmartFactory.ExcludedFields.put('Opportunity',new Set<String>{'rh2__Describe__c'});
        SmartFactory.ExcludedFields.put('Opportunity',new Set<String>{'pse__Current_Time_Period__c'});
        SmartFactory.ExcludedFields.put('Opportunity',new Set<String>{'DNBoptimizer__DnBContactRecord__c'});
        SmartFactory.ExcludedFields.put('Opportunity',new Set<String>{'pse__Actuals_Last_Updated_By__c'});
        
        Contact contact = (Contact)SmartFactory.createSObject('Contact', true);
        insert contact;
        System.assert(contact.Id != null);
        System.assert(contact.AccountId != null);
    }*/
    
    static testMethod void createsObjectWithoutCascadeDoesNotSetLookupField() {
        Contact contact = (Contact)SmartFactory.createSObject('Contact', false);
        contact.Contact_Status__c = 'Recycle';// to avoid System.DmlException: Insert failed. First exception on row 0; first error: INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST, bad value for restricted picklist field: Authority: [Contact_Status_Detail__c]	
        contact.Contact_Status_Detail__c = 'Authority';// to avoid System.DmlException: Insert failed. First exception on row 0; first error: INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST, bad value for restricted picklist field: Authority: [Contact_Status_Detail__c]	
        insert contact;
        System.assert(contact.AccountId == null);
    }
    
    static testMethod void createObjectWithUnsupportedTypeThrowsException() {
        try {
            SmartFactory.createSObject('Unsupported');
            System.assert(false);
        } catch (UnsupportedObjectTypeException ex) {
            System.assert(true);
        }
    }
}