src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Imported_from_Whitespace__c</fullName>
        <description>This field is part of the Traction Hierarchy app implementation. It will be auto-populated whenever an Account is created through the Traction Hierarchy app using Whitespace. Do NOT change field type to Checkbox as it will not work with Traction. 
JIRA: SFDCSPT-149</description>
        <inlineHelpText>This field is auto-populated whenever an Account is created through the Traction Hierarchy app using Whitespace.</inlineHelpText>
        <label>Imported from Whitespace</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Closed_Lost_Competitor__c</fullName>
        <businessOwnerGroup>Sales</businessOwnerGroup>
        <description>JIRA: SFDCSPT-289; SFDCSPT-459; SFDCSPT-633</description>
        <inlineHelpText>Select the name of the competitor to which the Opportunity has been lost.</inlineHelpText>
        <label>Closed Lost Competitor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AgensGraph</fullName>
                </value>
                <value>
                    <fullName>Alibaba graph</fullName>
                </value>
                <value>
                    <fullName>AllegroGraph</fullName>
                </value>
                <value>
                    <fullName>Amazon (AWS) Neptune</fullName>
                </value>
                <value>
                    <fullName>AnzoGraph DB</fullName>
                </value>
                <value>
                    <fullName>Arango DB</fullName>
                </value>
                <value>
                    <fullName>AtomRain</fullName>
                </value>
                <value>
                    <fullName>Aura Professional</fullName>
                </value>
                <value>
                    <fullName>BigQuery</fullName>
                </value>
                <value>
                    <fullName>Blazegraph</fullName>
                </value>
                <value>
                    <fullName>Cassandra</fullName>
                </value>
                <value>
                    <fullName>DataStax</fullName>
                </value>
                <value>
                    <fullName>Dgraph</fullName>
                </value>
                <value>
                    <fullName>Fauna</fullName>
                </value>
                <value>
                    <fullName>FEDRAMP High Required</fullName>
                </value>
                <value>
                    <fullName>FEDRAMP Medium Required</fullName>
                </value>
                <value>
                    <fullName>FlockDB</fullName>
                </value>
                <value>
                    <fullName>Fluree</fullName>
                </value>
                <value>
                    <fullName>Giraph</fullName>
                </value>
                <value>
                    <fullName>GraphBase</fullName>
                </value>
                <value>
                    <fullName>GraphDB</fullName>
                </value>
                <value>
                    <fullName>Graph Engine</fullName>
                </value>
                <value>
                    <fullName>HGraphDB</fullName>
                </value>
                <value>
                    <fullName>HugeGraph</fullName>
                </value>
                <value>
                    <fullName>HyperGraphDB</fullName>
                </value>
                <value>
                    <fullName>InfiniteGraph</fullName>
                </value>
                <value>
                    <fullName>JanusGraph</fullName>
                </value>
                <value>
                    <fullName>Memgraph</fullName>
                </value>
                <value>
                    <fullName>Microsoft Azure Cosmos DB</fullName>
                </value>
                <value>
                    <fullName>Mongo DB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Loss_Reason__c</fullName>
        <description>To track the reasons Opportunities are moved to Closed Lost. SFDCSPT-289</description>
        <inlineHelpText>Select the reason this Opportunity was marked as Closed Lost.</inlineHelpText>
        <label>Loss Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Loss - 1% Not Qualified</fullName>
                </value>
                <value>
                    <fullName>Loss - Competition</fullName>
                </value>
                <value>
                    <fullName>Loss - Default on Payment</fullName>
                </value>
                <value>
                    <fullName>Loss - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Loss - FEDRAMP</fullName>
                </value>
                <value>
                    <fullName>Loss - Keep Existing Solution</fullName>
                </value>
                <value>
                    <fullName>Loss - Lack of functionality</fullName>
                </value>
                <value>
                    <fullName>Loss - No Budget or Approved Project</fullName>
                </value>
                <value>
                    <fullName>Loss - No Decision</fullName>
                </value>
                <value>
                    <fullName>Loss - No Response</fullName>
                </value>
                <value>
                    <fullName>Loss - Price</fullName>
                </value>
                <value>
                    <fullName>Loss - Product Instability</fullName>
                </value>
                <value>
                    <fullName>Loss - Project Delayed/Pushed-Out</fullName>
                </value>
                <value>
                    <fullName>Renewal - Acquisition/Merger</fullName>
                </value>
                <value>
                    <fullName>Renewal - Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>Renewal - Change in Business Direction</fullName>
                </value>
                <value>
                    <fullName>Renewal - Default on Payment</fullName>
                </value>
                <value>
                    <fullName>Renewal - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Renewal - Lack of Adoption</fullName>
                </value>
                <value>
                    <fullName>Renewal - Lack of perceived Value</fullName>
                </value>
                <value>
                    <fullName>Renewal - Lost Champion</fullName>
                </value>
                <value>
                    <fullName>Renewal - Project Canceled</fullName>
                </value>
                <value>
                    <fullName>Renewal - Project Never Implemented</fullName>
                </value>
                <value>
                    <fullName>Renewal - Loss of Budget</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sugar_ID__c</fullName>
        <externalId>true</externalId>
        <label>Sugar ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Use_Case_Sub__c</fullName>
        <description>Subecategory Use cases</description>
        <label>Use Case Subcategory</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Use_Case__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Anti Money Laundering</fullName>
                </value>
                <value>
                    <fullName>Claim Processing</fullName>
                </value>
                <value>
                    <fullName>Compliance meta-data (GDPR, BSBS 239, MiFID II, Other)</fullName>
                </value>
                <value>
                    <fullName>Credit Risk Management</fullName>
                </value>
                <value>
                    <fullName>Customer 360 / KYC</fullName>
                </value>
                <value>
                    <fullName>Cyber Security</fullName>
                </value>
                <value>
                    <fullName>Data Governance</fullName>
                </value>
                <value>
                    <fullName>Data Integration</fullName>
                </value>
                <value>
                    <fullName>Digital Media MDM</fullName>
                </value>
                <value>
                    <fullName>Employee MDM</fullName>
                </value>
                <value>
                    <fullName>Enterprise MDM</fullName>
                </value>
                <value>
                    <fullName>Fraud Detection</fullName>
                </value>
                <value>
                    <fullName>Graph Analytics</fullName>
                </value>
                <value>
                    <fullName>Intelligence</fullName>
                </value>
                <value>
                    <fullName>Master Data (Customer 360 / KYC, Employee / Product / Sales / Supply Chain / Other)</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Product MDM</fullName>
                </value>
                <value>
                    <fullName>Sales MDM</fullName>
                </value>
                <value>
                    <fullName>Supply Chain MDM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Use_Case__c</fullName>
        <businessOwnerGroup>Sales</businessOwnerGroup>
        <description>This picklist contains values that apply to different use cases -- how and/or why the customer will use product(s). JIRA: SFDCSPT-460</description>
        <inlineHelpText>Select the value that best describes how and/or why the prospect will use the product(s) included in this oppotrunity.</inlineHelpText>
        <label>Use Case</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Embedded</fullName>
                </value>
                <value>
                    <fullName>Graph Based Search</fullName>
                </value>
                <value>
                    <fullName>Identity and Access Management</fullName>
                </value>
                <value>
                    <fullName>Knowledge Graph</fullName>
                </value>
                <value>
                    <fullName>Master &amp; Meta-Data Management</fullName>
                </value>
                <value>
                    <fullName>Network and IT Operations</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>Recommendations</fullName>
                </value>
                <value>
                    <fullName>Risk Management</fullName>
                </value>
                <value>
                    <fullName>Solutions Lab</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <businessProcess>New</businessProcess>
        <label>New</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <externalId>true</externalId>
        <label>Opportunity ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductType__c</fullName>
        <label>Product Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <businessOwnerGroup>Sales_Operations</businessOwnerGroup>
        <description>This field is to specify whether the Opportunity Item is New, Up-Sell, Cross-Sell or Renewal.</description>
        <inlineHelpText>Select one of the applicable values from the picklist.</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Up-Sell</fullName>
                </value>
                <value>
                    <fullName>Cross-Sell</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sugar_ID__c</fullName>
        <externalId>true</externalId>
        <label>Sugar ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Sugar_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Sugar ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Trigger_OpportunityLineItemTest.cls
@isTest
private class Trigger_OpportunityLineItemTest {
    private static testmethod void populateProductTest01(){
        
        Id pricebookId = Test.getStandardPricebookId();
        
        //Create your product
        Product2 prod = new Product2( Name = 'Test Type',
                                      ProductCode = 'Pro-X',
                                      isActive = true );
        insert prod;
        
        //Create your pricebook entry
        PricebookEntry pbEntry = new PricebookEntry( Pricebook2Id = pricebookId,
                                                     Product2Id = prod.Id,
                                                     UnitPrice = 100.00,
                                                     IsActive = true );
        insert pbEntry;
        
        //create your opportunity
        Opportunity opp = new Opportunity( Name = 'Test Opportunity',
                                           StageName = 'Qualification',
                                           CloseDate = System.today(),
                                           Sugar_ID__c = 'Opp' );
        insert opp;
            
        //create your opportunity line item.
        OpportunityLineItem oli = new OpportunityLineItem( Opportunity_ID__c = 'Opp',
                                                           Quantity = 1, //qty must be one (1) to satisfy a validation rule.
                                                           PricebookEntryId = pbEntry.Id,
                                                           UnitPrice = 10,
                                                           ProductType__c = 'Test Type',
                                                           Product_Type__c='New');
        test.startTest();
        insert oli;
        test.stopTest();
        
        //Opportunity Line After Update.
        OpportunityLineItem oppLineAfterUpdate = [ SELECT Id, Name, Product2Id, OpportunityId
                                                   FROM OpportunityLineItem WHERE Id = : oli.id ];
        System.assertEquals( oppLineAfterUpdate.Product2Id, prod.Id );
        System.assertEquals( oppLineAfterUpdate.OpportunityId, opp.Id );
    }
    private static testmethod void populateProductTest02(){
        
        Id pricebookId = Test.getStandardPricebookId();
        
        //Create your product
        Product2 prod = new Product2( Name = 'Test Type',
                                      ProductCode = 'Pro-X',
                                      isActive = true );
        insert prod;
        
        //Create your pricebook entry
        PricebookEntry pbEntry = new PricebookEntry( Pricebook2Id = pricebookId,
                                                     Product2Id = prod.Id,
                                                     UnitPrice = 100.00,
                                                     IsActive = true );
        insert pbEntry;
        Opportunity opp = new Opportunity( Name = 'Test Opportunity',
                                           StageName = 'Qualification',
                                           CloseDate = System.today(),
                                           Sugar_ID__c = 'Opp' );
        insert opp;
            
        //create your opportunity line item.
        OpportunityLineItem oli = new OpportunityLineItem( OpportunityId = opp.Id,
                                                           Quantity = 1, //qty must be one (1) to satisfy a validation rule.
                                                           PricebookEntryId = pbEntry.Id,
                                                           UnitPrice = 10,
                                                           ProductType__c = 'Test Type',
                                                           Product_Type__c='New');
        OpportunityLineItemTriggerHelper.runTrigger = FALSE;
        insert oli;
    }

    //start neo4j common/standard testSetup. SFDC-0503- todo DRY the testSetup methods into a factory class<https://neo4j--organizer.na141.visual.force.com/a7z4o000000GrYbAAK>
    @testSetup static void setupPricingData() { //Use test setup methods (methods that are annotated with @testSetup) to create test records once and then access them in every test method in the test class.
        //If a test class contains a test setup method, the testing framework executes the test setup method first, before any test method in the class.
        //Records that are created in a test setup method are available to all test methods in the test class and are rolled back at the end of test class execution. 
        //If a test method changes those records, such as record field updates or record deletions, those changes are rolled back after each test method finishes execution. 
        //The next executing test method gets access to the original unmodified state of those records
        //source=https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_testing_testsetup_using.htm
        
        SmartFactory.FillAllFields=true;
       
        //excluded Opportunity TestSetup Fields
        /** more information about this classes testsetup and its smartfactory Excluded Fields:
         * OwnerId is excluded in setupsetup because we use the testing user instead.
         * Closed_Lost_Competitor__c is excluded because validation rule msg "Closed Lost Competitor field is only used for Closed Lost opps with Loss Reason Competition"
         * Loss_Reason__c is excluded beacuse validation rule msg "Loss Reason is only used when Sales Stage is Closed Lost"
        */
        SmartFactory.ExcludedFields.put('Opportunity',new Set<String>{'OwnerId','Closed_Lost_Competitor__c','Loss_Reason__c'});

        Account acct = (Account)SmartFactory.createSObject('Account');
        acct.BillingCountry = 'United States'; //this intends to bypass state/country picklist validation error (There's a problem with this country, even though it may appear correct. Please select a country/territory from the list of valid countries)
        acct.BillingCountryCode ='US'; //this intends to bypass state/country picklist validation error (There's a problem with this country, even though it may appear correct. Please select a country/territory from the list of valid countries)
        acct.BillingState ='Washington'; //this intends to bypass state/country picklist validation error (There's a problem with this country, even though it may appear correct. Please select a country/territory from the list of valid countries)
        acct.BillingStateCode = 'WA'; //this intends to bypass state/country picklist validation error (There's a problem with this country, even though it may appear correct. Please select a country/territory from the list of valid countries)
        acct.ShippingCountry = 'United States'; //this intends to bypass state/country picklist validation error (There's a problem with this country, even though it may appear correct. Please select a country/territory from the list of valid countries)
        acct.ShippingCountryCode= 'US'; //this intends to bypass state/country picklist validation error (There's a problem with this country, even though it may appear correct. Please select a country/territory from the list of valid countries)
        acct.ShippingState = 'Washington'; //this intends to bypass state/country picklist validation error (There's a problem with this country, even though it may appear correct. Please select a country/territory from the list of valid countries)
        acct.ShippingStateCode='WA';//this intends to bypass state/country picklist validation error (There's a problem with this country, even though it may appear correct. Please select a country/territory from the list of valid countries)
        acct.Imported_from_Whitespace__c='0'; //at time of writing, its a text field,  and we set it to '0' here so that it does not enter the "Enrich Whitespace Created Accounts" flow, because that flow was failing when we had set this to 1.
        
        try{
            insert acct;
        }catch(Exception e){
            system.debug(e.getStackTraceString() + e.getCause());
        }
        

        Opportunity opp = (Opportunity)SmartFactory.createSObject('Opportunity');
        opp.AccountId = acct.Id;
        opp.Use_Case__c='Risk Management'; //because Use_Case__c & Use_Case_Sub__c may be restricted and picklist dependent
        opp.Use_Case_Sub__c='Anti Money Laundering'; //because Use_Case__c & Use_Case_Sub__c may be restricted and picklist dependent

        insert opp;
        
        // Create common test Product, Pricebook, and PbEntries.
        // First, set up test price book entries.
        // Insert a test product.
        Product2 prod = new Product2(Name = 'Test Product ARRCalc/a7z3s0000004SGsAAM', 
            Family = 'Hardware');
        insert prod;
        // Get standard price book ID.
        // This is available irrespective of the state of SeeAllData.
        Id pricebookId = Test.getStandardPricebookId();
        // 1. Insert a price book entry for the standard price book.
        // Standard price book entries require the standard price book ID we got earlier.
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod.Id,
            UnitPrice = 10000, IsActive = true);
        insert standardPrice;
        // Create a custom price book
        Pricebook2 customPB = new Pricebook2(Name='Custom Pricebook', isActive=true);
        insert customPB;
        // 2. Insert a price book entry with a custom price.
        PricebookEntry customPrice = new PricebookEntry(
            Pricebook2Id = customPB.Id, Product2Id = prod.Id,
            UnitPrice = 12000, IsActive = true);
        insert customPrice;
        // Next, perform some tests with your test price book entries.
    }
    //end neo4j common/standard testSetup. SFDC-0503- todo DRY the testSetup methods into a factory class<https://neo4j--organizer.na141.visual.force.com/a7z4o000000GrYbAAK>
    
    @IsTest
    static void test_arrCalc_beforeInsert_OLI_with_calcVariables(){
        
        //Given that @testSetup creates an Account, Opportunity, PricebookEntry, PricebookEntry.
        
        Test.startTest();
        
        //When we have arrCalc variables during OLI insert
        
        Test.stopTest();

        //We expect arr to be derived from those variables per business formula: 
        
    }
    
    @IsTest
    static void test_arrCalc_beforeInsert_OLI_without_calcVariables(){
        //Given that @testSetup creates an Account, Opportunity, PricebookEntry, PricebookEntry.
        
        Test.startTest();
        
        //When OLI inserts    
        
        Test.stopTest();

        //We expect ARR to remain unchanged
        
    }

    @IsTest
    static void test_arrCalc_beforeInsert_OLI_with_exception(){
        //setup
        
        //Given that @testSetup creates an Account, Opportunity, PricebookEntry, PricebookEntry.
        
        Test.startTest();
        
        //When an exception occurs during OLI insert
        
        Test.stopTest();

        //We expect arr to remain unchanged
        
    }


}