src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/License_Key__c.object
<CustomObject>
    <description>Object used for storing Neo4J license keys</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>License_Keys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Activation Keys</relationshipLabel>
        <relationshipName>License_Keys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email associated with the license key</description>
        <inlineHelpText>Email associated with the license key</inlineHelpText>
        <label>Key recipient email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>Expiration date for the license key</description>
        <inlineHelpText>Expiration date for the license key</inlineHelpText>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>License_Keys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with License Key request</description>
        <inlineHelpText>Opportunity associated with License Key request</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>License_Keys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <description>Name of the organization associated with the license key</description>
        <inlineHelpText>Name of the organization associated with the license key</inlineHelpText>
        <label>Organization</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Number of user licenses associated with the key</description>
        <inlineHelpText>Number of user licenses associated with the key</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Registrant__c</fullName>
        <description>Name of the contact associated with the key</description>
        <inlineHelpText>Name of the contact associated with the key</inlineHelpText>
        <label>Registrant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of key requested</description>
        <inlineHelpText>Type of key requested</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Trial</fullName>
                </value>
                <value>
                    <fullName>Production</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>X_Generate_License_Key__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Internal field for triggering the fetching of new license key from the key server</description>
        <inlineHelpText>Internal field for triggering the fetching of new license key from the key server</inlineHelpText>
        <label>X_Generate_License_Key</label>
        <type>Checkbox</type>
    </fields>
    <label>Activation Key</label>
    <nameField>
        <displayFormat>LK-{0000}</displayFormat>
        <label>License Key Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activation Keys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Neo4J_License_Generation_Service__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings associated with Neo4J license key generation service</description>
    <fields>
        <fullName>Default_License_Key_Duration_for_Leads__c</fullName>
        <description>Default duration (days) license keys generated for leads</description>
        <inlineHelpText>Default duration (days) license keys generated for leads</inlineHelpText>
        <label>Default License Key Duration for Leads</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Neo4J License Generation Service</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <businessProcess>New</businessProcess>
        <label>New</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/N4J_LicenseKeyRequest.cls
public class N4J_LicenseKeyRequest {
    
    public boolean renderForm {get; set;} //flag to render the form
    public License_Key__c lkey {get; set;} //license key object
    public SObject sobj {get; set;} //opportunity/contact/lead associated with the request
    public Account accnt {get; set;} //account associated with the request, if any
    public Neo4J_License_Generation_Service__c cs {get; set;}
    
    //constructor used by all License Key Request Pages
	public N4J_LicenseKeyRequest(ApexPages.StandardController sc){
        lkey = new License_Key__c();
        sobj = sc.getRecord();
        renderForm = false;
        cs = Neo4J_License_Generation_Service__c.getInstance();
    }
    
    
    //defaults the values based on the involved opportunity/contact/lead
    public PageReference defaultKeyRequestDetails(){
        if(sobj.getSObjectType() == Schema.Opportunity.getSObjectType()){ //page is invoked from opportunity
            Opportunity o = [SELECT AccountId, Account.Name FROM Opportunity WHERE Id = :sobj.Id];
            accnt = new Account(Id = o.AccountId, Name = o.Account.Name);
            lkey.Account__c = o.AccountId;
            lkey.Type__c = 'Production';
            //default the primary contact for the opportunity
            List<OpportunityContactRole> lstOCR = [SELECT ContactId, Contact.Email
                                                     FROM OpportunityContactRole
                                                    WHERE OpportunityId = :sobj.Id
                                                      AND IsPrimary = TRUE];
            if(!lstOCR.isEmpty() && lstOCR.get(0).Contact.Email != null){
                lKey.Contact__c = lstOCR.get(0).ContactId;
            }
        }
        if(sobj.getSObjectType() == Schema.Lead.getSObjectType()){ //page is invoked from lead
            //default the expiration date
            lkey.Expiration_Date__c = Date.today().addDays(cs == null || cs.Default_License_Key_Duration_for_Leads__c == null ?
                                                           30 : Integer.valueOf(cs.Default_License_Key_Duration_for_Leads__c));
            lkey.Lead__c = sobj.Id;
            lkey.Type__c = 'Trial';
        }
        if(sobj.getSObjectType() == Schema.Contact.getSObjectType()){ //page is invoked from opportunity
            Contact c = [SELECT AccountId, Account.Name FROM Contact WHERE Id = :sobj.Id];
            accnt = new Account(Id = c.AccountId, Name = c.Account.Name);
            lkey.Account__c = c.AccountId;
            lKey.Contact__c = sobj.id;
            lkey.Type__c = 'Trial';
        }
        
        lkey.Expiration_Date__c = Date.today().addDays(cs == null || cs.Default_License_Key_Duration_for_Leads__c == null ?
                                                           30 : Integer.valueOf(cs.Default_License_Key_Duration_for_Leads__c));
        lkey.Type__c = 'Trial';
        
        ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.INFO,     '<H3>Important Notes</H3>' + 
                                                                                   '<UL><LI>Key type = <B><I>Trial</I></B> can be issued by anyone with access to this form.</LI>' +
                                                                                   '<LI>Key type = <B><I>Production</I></B> should only be issued by the Customer Success team and the key should tie to the <B><I>Closed-Won</I></B> opportunity.</LI>' +
                                                                                   '<LI>Only 1 key per product per opportunity is necessary for either <B><I>Trial</I></B> or <B><I>Production</I></B> purposes. If multiple users on the project need a key, indicate the number of users in the Quantity field, and then generate 1 key to go to the primary contact. Once generated, the email containing the key can be forwarded to other recipients who need it.</LI>' + 
                                                                                   '<LI>For <B><I>Production</I></B> keys, set the expiration date to the last date of the contract.</LI></UL>');
        ApexPages.addMessage(msg);
        
        renderForm = true;
        return null;
    }
    
    public PageReference redirectBack(){
        return new PageReference('/' + sobj.Id); 
    }
    
    public PageReference initiateKeyRequest(){
        
        ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.INFO,     '<H3>Important Notes</H3>' + 
                                                                                   '<UL><LI>Key type = <B><I>Trial</I></B> can be issued by anyone with access to this form.</LI>' +
                                                                                   '<LI>Key type = <B><I>Production</I></B> should only be issued by the Customer Success team and the key should tie to the <B><I>Closed-Won</I></B> opportunity.</LI>' +
                                                                                   '<LI>Only 1 key per product per opportunity is necessary for either <B><I>Trial</I></B> or <B><I>Production</I></B> purposes. If multiple users on the project need a key, indicate the number of users in the Quantity field, and then generate 1 key to go to the primary contact. Once generated, the email containing the key can be forwarded to other recipients who need it.</LI>' + 
                                                                                   '<LI>For <B><I>Production</I></B> keys, set the expiration date to the last date of the contract.</LI></UL>');
        ApexPages.addMessage(msg);
        
        if(lkey.Expiration_Date__c < Date.today()){
            lkey.Expiration_Date__c.addError('Expiration Date for the license key cannot be in the past');
            return null;
        }
        if(lkey.Quantity__c < 1 || lkey.Quantity__c > 100000 ){
            lkey.Quantity__c.addError('Quantity must be between 1 and 100,000');
            return null;
        }
        
        if(lkey.Expiration_Date__c < Date.today()){
            lkey.Expiration_Date__c.addError('Expiration Date for the license key cannot be in the past');
            return null;
        }
        if(sobj.getSObjectType() == Schema.Opportunity.getSObjectType() || 
           sobj.getSObjectType() == Schema.Contact.getSObjectType()){
               //check if the contact has an email address
               Contact c = [SELECT Name, Email FROM Contact WHERE Id = :lkey.Contact__c];
               if(c.Email == null){
                   ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Error,
                               'Selected contact record does not have an email address. Please specify an email address by clicking' +
                               '<a href="/' + lkey.Contact__c + '" target="_new"> here </a>'));
                   return null;
               }
          lkey.Email__c = c.Email;
          lkey.Organization__c = accnt.name;
          lkey.Registrant__c = c.Name;
        }
        if(sobj.getSObjectType() == Schema.Opportunity.getSObjectType()){
            lkey.Opportunity__c = sObj.Id;
        }
        if(sobj.getSObjectType() == Schema.Lead.getSObjectType()){
             //check if the lead has an email address and company name
            Lead l = [SELECT Name, Company, Email FROM Lead WHERE Id = :sobj.id];
            if(l.Email == null){
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Error,
                               'Lead record does not have an email address. Please specify an email address by clicking' +
                               '<a href="/' + sobj.id + '" target="_new"> here </a>'));
                return null;
            }
            lkey.Email__c = l.Email;
            lkey.Registrant__c = l.Name;
            lkey.Organization__c = l.Company;                    
         
        }
        lkey.X_Generate_License_Key__c = true;
        INSERT lkey;
        return new PageReference('/' + lkey.Id);
    }
    
}